before_script:
  - npm install
  - cd client && npm install --suppress-optional fsevents@1.2.7
script:
  - npm run linter
  - npm run client-tests
  - npm run client-commit-check
language: node_js
env:
  - PORT=7777
node_js:
  - '10'
  - '9'
