version: '3.3'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run server"
    ports:
      - "5000:3000"
  
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    command: "npm run client"
    volumes:
      - ./client/src:/var/www/ytracker/client/src
      - ./client/public:/var/www/ytracker/client/public
    ports:
      - "3000:3000"
    links:
      - server
    depends_on:
      - server