const companyConstants = {
  REGISTERING_COMPANY: 'REGISTERING_COMPANY',
  REGISTER_COMPANY_SUCCESS: 'REGISTER_COMPANY_SUCCESS',
  REGISTER_COMPANY_FAIL: 'REGISTER_COMPANY_FAIL',
  CLEAR_COMPANY_REGISTRATION: 'CLEAR_COMPANY_REGISTRATION',
  UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
  UPDATE_COMPANY_FAIL: 'UPDATE_COMPANY_FAIL',
  GET_ALL_COMPANIES_REQUEST: 'GET_ALL_COMPANIES_REQUEST',
  GET_ALL_COMPANIES_SUCCESS: 'GET_ALL_COMPANIES_SUCCESS',
  GET_ALL_COMPANIES_FAIL: 'GET_ALL_COMPANIES_FAIL',
  LOAD_COMPANY_REQUEST: 'LOAD_COMPANY_REQUEST',
  LOAD_COMPANY_SUCCESS: 'LOAD_COMPANY_SUCCESS',
  LOAD_COMPANY_FAIL: 'LOAD_COMPANY_FAIL',
  CLEAR_SELECTED_COMPANY: 'CLEAR_SELECTED_COMPANY',
  CLEAR_COMPANIES: 'CLEAR_COMPANIES',
};

export default companyConstants;
