const profileConstants = {
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',
  PROFILE_LOADING: 'PROFILE_LOADING',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  CLEAR_CURRENT_PROFILE: 'CLEAR_CURRENT_PROFILE',
  CREATE_USER_PROFILE_REQUEST: 'CREATE_USER_PROFILE_REQUEST',
  CREATE_USER_PROFILE_SUCCESS: 'CREATE_USER_PROFILE_SUCCESS',
  CREATE_USER_PROFILE_FAIL: 'CREATE_USER_PROFILE_FAIL',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
};

export default profileConstants;
