const profileConstants = {
  GET_PROFILE: 'GET_PROFILE',
  PROFILE_LOADING: 'PROFILE_LOADING',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  CLEAR_CURRENT_PROFILE: 'CLEAR_CURRENT_PROFILE',
  CREATE_USER_PROFILE: 'CREATE_USER_PROFILE',
};

export default profileConstants;
