const serviceConstants = {
  ADD_YACHT_SERVICE: 'ADD_YACHT_SERVICE',
  ADD_YACHT_SERVICE_SUCCESS: 'ADD_YACHT_SERVICE_SUCCESS',
  ADD_YACHT_SERVICE_FAIL: 'ADD_YACHT_SERVICE_FAIL',
  CLEAR_YACHT_SERVICE: 'CLEAR_YACHT_SERVICE',
};

export default serviceConstants;
