const yachtConstants = {
  GET_ALL_YACHTS_REQUEST: 'GET_ALL_YACHTS_REQUEST',
  GET_ALL_YACHTS_SUCCESS: 'GET_ALL_YACHTS_SUCCESS',
  GET_ALL_YACHTS_FAIL: 'GET_ALL_YACHTS_FAIL',
  GET_ALL_ACTIVE_YACHTS_REQUEST: 'GET_ALL_ACTIVE_YACHTS_REQUEST',
  GET_ALL_ACTIVE_YACHTS_SUCCESS: 'GET_ALL_ACTIVE_YACHTS_SUCCESS',
  GET_ALL_ACTIVE_YACHTS_FAIL: 'GET_ALL_ACTIVE_YACHTS_FAIL',
  LOAD_YACHT_REQUEST: 'LOAD_YACHT_REQUEST',
  LOAD_YACHT_SUCCESS: 'LOAD_YACHT_SUCCESS',
  LOAD_YACHT_FAIL: 'LOAD_YACHT_FAIL',
  CLEAR_SELECTED_YACHT: 'CLEAR_SELECTED_YACHT',
  CLEAR_YACHTS: 'CLEAR_YACHTS',
  REGISTERING_YACHT: 'REGISTERING_YACHT',
  REGISTER_YACHT_SUCCESS: 'REGISTER_YACHT_SUCCESS',
  REGISTER_YACHT_FAIL: 'REGISTER_YACHT_FAIL',
  CLEAR_YACHT_REGISTRATION: 'CLEAR_YACHT_REGISTRATION',
  UPDATE_YACHT_SUCCESS: 'UPDATE_YACHT_SUCCESS',
  UPDATE_YACHT_FAIL: 'UPDATE_YACHT_FAIL',
};

export default yachtConstants;
