export const selectedYacht = {
  _id: '',
  name: '',
  email: '',
  yachttype: '',
  active: true,
  phone: '',
  loa: 0,
  draft: 0,
  beam: 0,
  grosstonnage: 0,
  buildcompany: '',
  buildyear: 0,
  refityear: 0,
  cruisinglicense: '',
  taxid: '',
  billingcompany: {
    name: '',
    email: '',
    phone: '',
    mobile: '',
    address: {
      addressline1: '',
      addressline2: '',
      city: '',
      postalcode: '',
      country: '',
    },
  },
  owningcompany: {
    name: '',
    email: '',
    phone: '',
    mobile: '',
    address: {
      addressline1: '',
      addressline2: '',
      city: '',
      postalcode: '',
      country: '',
    },
  },
  managementcompany: {
    name: '',
    email: '',
    phone: '',
    mobile: '',
    address: {
      addressline1: '',
      addressline2: '',
      city: '',
      postalcode: '',
      country: '',
    },
  },
}
