export const selectedYacht = {
  _id: '',
  name: '',
  email: '',
  yachttype: '',
  active: true,
  phone: '',
  loa: '',
  draft: '',
  beam: '',
  grosstonnage: '',
  buildcompany: '',
  buildyear: '',
  refityear: '',
  cruisinglicense: '',
  taxid: '',
  billingcompany: {
    name: '',
    email: '',
    phone: '',
    mobile: '',
    address: {
      addressline1: '',
      addressline2: '',
      city: '',
      postalcode: '',
      country: '',
    },
  },
  owningcompany: {
    name: '',
    email: '',
    phone: '',
    mobile: '',
    address: {
      addressline1: '',
      addressline2: '',
      city: '',
      postalcode: '',
      country: '',
    },
  },
  managementcompany: {
    name: '',
    email: '',
    phone: '',
    mobile: '',
    address: {
      addressline1: '',
      addressline2: '',
      city: '',
      postalcode: '',
      country: '',
    },
  },
}
